# this file stores all the project-wide configuration in one place.
# here we are following DRY (Don't Repeat Yourself) principle, so that we can easily manage and update configurations without having to change them in multiple places. 
"""
==========================================================
                AI Receptionist Prototype
                    Configuration File
==========================================================

Purpose:
--------
This file stores all project-wide configuration such as:

1. API Keys
2. API URLs
3. AI Model Names
4. Audio File Paths
5. LLM Parameters

Keeping everything here makes the project easy to
maintain and update.


==========================================================
"""

# ==========================================================
# Import Required Libraries
# ==========================================================

import os
from dotenv import load_dotenv


# ==========================================================
# Load Environment Variables
# ==========================================================

# Read variables from the .env file
load_dotenv()


# ==========================================================
# Hugging Face Configuration
# ==========================================================

# Read Hugging Face API Token from .env
HF_API_KEY = os.getenv("HF_TOKEN")

# Hugging Face OpenAI-compatible endpoint
HF_BASE_URL = "https://router.huggingface.co/v1"


# ==========================================================
# AI Model Configuration
# ==========================================================

# Large Language Model (LLM)
LLM_MODEL = "Qwen/Qwen2.5-1.5B-Instruct:featherless-ai"

# Whisper Speech-to-Text model
WHISPER_MODEL = "base"

# Piper Text-to-Speech model
PIPER_MODEL = os.path.join(
    "models",
    "en_US-lessac-medium.onnx")


# ==========================================================
# Audio File Paths
# ==========================================================

# Folder where input audio files will be stored
INPUT_FOLDER = "input"

# Folder where generated audio will be stored
OUTPUT_FOLDER = "output"

# Default patient audio file
INPUT_AUDIO_FILE = os.path.join(INPUT_FOLDER, "patient.wav")

# Default AI generated audio
OUTPUT_AUDIO_FILE = os.path.join(OUTPUT_FOLDER, "output.wav")


# ==========================================================
# LLM Configuration
# ==========================================================

# Maximum number of tokens generated by the LLM
MAX_TOKENS = 150

# Controls randomness of responses
# 0.0 = Deterministic
# 1.0 = More Creative
TEMPERATURE = 0.5


# ==========================================================
# Validation
# ==========================================================

if not HF_API_KEY:
    raise ValueError(
        "HF_TOKEN not found!\n"
        "Please create a .env file and add:\n\n"
        "HF_TOKEN=your_huggingface_api_key"
    )


# Audio Recording Settings
SAMPLE_RATE = 16000
CHANNELS = 1
AUDIO_DTYPE = "int16"

INPUT_FOLDER="input"
INPUT_AUDIO_FILE = os.path.join(INPUT_FOLDER,"patient.wav")


#To centralize all configuration like API keys, model names, file paths, and LLM settings. This avoids duplication, makes maintenance easier, and allows changes in one place without modifying multiple modules.
# print("=" * 50)
# print("HF_API_KEY:", HF_API_KEY)
# print("=" * 50)